import {config} from 'dotenv'
config();

const {PORT, 
    LLM_MODEL, 
    LLM_API_KEY, 
    LLM_BASE_URL,
    AI_DATABASE_URL,
    POSTGRES_DATABASE_URL,
    LANGSMITH_API_KEY,
    SCRAPER_API_KEY,
    TRAVILY_WEB_SEARCH_API_KEY,
    LANGSMITH_TRACING,
    LANGSMITH_ENDPOINT,
    LANGSMITH_PROJECT,

   
} = process.env;

export const _config = {
PORT,
LLM_MODEL,
LLM_API_KEY,
LLM_BASE_URL,
AI_DATABASE_URL,
POSTGRES_DATABASE_URL,
LANGSMITH_API_KEY,
SCRAPER_API_KEY,
TRAVILY_WEB_SEARCH_API_KEY,
LANGSMITH_TRACING,
LANGSMITH_ENDPOINT,
LANGSMITH_PROJECT,
}
